on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
        -  mathcomp/mathcomp:2.4.0-coq-8.20
        -  mathcomp/mathcomp:2.5.0-coq-8.20
        -  mathcomp/mathcomp:2.4.0-rocq-prover-9.0
        -  mathcomp/mathcomp:2.5.0-rocq-prover-9.0
        -  mathcomp/mathcomp:2.4.0-rocq-prover-9.1
        -  mathcomp/mathcomp:2.5.0-rocq-prover-9.1
        -  mathcomp/mathcomp:2.6.0-rocq-prover-9.2
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
    - uses: rocq-community/docker-coq-action@v1
      with:
        custom_image: ${{ matrix.image }}
        before_install: |
          startGroup "Workaround permission issue"
            sudo chown -R 1000:1000 .
          endGroup
          startGroup "Unpin dune"
            opam unpin dune
            opam pin add -n -k version dune 3.21.1
          endGroup
    - name: Revert permissions
      if: ${{ always() }}
      run: sudo chown -R 1001:116 .
